//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DW_Access
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dwdashboardEntities : DbContext
    {
        public dwdashboardEntities()
            : base("name=dwdashboardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dwCantidadMaletasPasajero> dwCantidadMaletasPasajero { get; set; }
        public virtual DbSet<dwDistribucionGenero> dwDistribucionGenero { get; set; }
        public virtual DbSet<dwMapaTopDestinos> dwMapaTopDestinos { get; set; }
        public virtual DbSet<dwTiempoVuelosEnRetraso> dwTiempoVuelosEnRetraso { get; set; }
        public virtual DbSet<dwTopAerolineas> dwTopAerolineas { get; set; }
        public virtual DbSet<dwVuelosPorEstado> dwVuelosPorEstado { get; set; }
        public virtual DbSet<dwGananciasTotales> dwGananciasTotales { get; set; }
        public virtual DbSet<dwGananciasPerdidas> dwGananciasPerdidas { get; set; }
    }
}
