//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DW_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class dwDistribucionGenero
    {
        public string Sexo { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public int Indice { get; set; }
    }
}
