//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DW_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class dwMapaTopDestinos
    {
        public string Aeropuerto { get; set; }
        public string Ciudad { get; set; }
        public string Pais { get; set; }
        public Nullable<double> LatX { get; set; }
        public Nullable<double> LonY { get; set; }
        public Nullable<int> ContadorVuelos { get; set; }
        public int Indice { get; set; }
    }
}
